# frozen_string_literal: true

require "spec_helper"

RSpec.describe SupportTableData::Documentation::RbsDoc do
  describe "#signatures" do
    it "returns nil when the model has no named instances" do
      allow(Color).to receive(:instance_names).and_return([])

      expect(described_class.new(Color).signatures).to be_nil
    end

    it "wraps signatures in a class declaration matching the model" do
      result = described_class.new(Color).signatures

      expect(result).to start_with("# Generated by support_table_data - do not edit by hand.\n")
      expect(result).to include("class Color\n")
      expect(result).to end_with("end\n")
    end

    it "emits a finder and predicate signature per named instance" do
      result = described_class.new(Color).signatures

      expect(result).to include("  def self.red: () -> Color")
      expect(result).to include("  def red?: () -> bool")
      expect(result).to include("  def self.blue: () -> Color")
      expect(result).to include("  def blue?: () -> bool")
    end

    it "uses RBS-flavoured types for attribute helper signatures" do
      result = described_class.new(Group).signatures

      # group_id is integer, name is string
      expect(result).to include("  def self.primary_group_id: () -> Integer")
      expect(result).to include("  def self.primary_name: () -> String")
    end

    it "sorts named instances alphabetically" do
      result = described_class.new(Color).signatures

      black_pos = result.index("def self.black:")
      blue_pos = result.index("def self.blue:")
      green_pos = result.index("def self.green:")
      red_pos = result.index("def self.red:")

      expect(black_pos).to be < blue_pos
      expect(blue_pos).to be < green_pos
      expect(green_pos).to be < red_pos
    end
  end
end
