# frozen_string_literal: true

namespace :support_table_data do
  desc "Syncronize data for all models that include SupportTableData."
  task sync: :environment do
    require_relative "utils"

    SupportTableData::Tasks::Utils.eager_load!

    logger_callback = lambda do |name, started, finished, unique_id, payload|
      klass = payload[:class]
      elapsed_time = finished - started
      message = "Synchronized support table model #{klass.name} in #{(elapsed_time * 1000).round}ms"
      if klass.logger
        klass.logger.info(message)
      else
        puts message
      end
    end

    ActiveSupport::Notifications.subscribed(logger_callback, "support_table_data.sync") do
      SupportTableData.sync_all!
    end
  end

  desc "Adds YARD documentation comments to models to document the named instance methods."
  task add_yard_docs: :environment do
    require_relative "../support_table_data/documentation"
    require_relative "utils"

    SupportTableData::Tasks::Utils.eager_load!

    ActiveRecord::Base.descendants.each do |klass|
      next unless klass.included_modules.include?(SupportTableData)
      next if klass.instance_names.empty?

      doc = SupportTableData::Documentation.new(klass)
      class_def_with_docs = doc.class_def_with_yard_docs
      next unless class_def_with_docs

      file_path = SupportTableData::Tasks::Utils.model_file_path(klass)
      next unless file_path&.file? && file_path.readable?

      begin_comment = "# Begin autogenerated YARD docs"
      end_comment = "# End autogenerated YARD docs"

      file_contents = File.read(file_path)
      updated_contents = file_contents.sub(/#{begin_comment}.*#{end_comment}/m, "").strip
      updated_contents = "#{updated_contents}\n\n#{begin_comment}\n#{class_def_with_docs}\n#{end_comment}\n"
      next if file_contents == updated_contents

      File.write(file_path, updated_contents)
      puts "Added YARD documentation to #{klass.name}."
    end
  end
end
