# frozen_string_literal: true

class Status < ActiveRecord::Base
  include SupportTableData

  self.support_table_key_attribute = :code
  add_support_table_data "statuses.yml"
  named_instance_attribute_helpers :name
end

# Begin autogenerated YARD docs
class Status
  # Find the named instance record +active+ from the database.
  #
  # @return [Status] the +active+ record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.active

  # Check if this record is the +active+ record.
  #
  # @return [Boolean] true if this is the +active+ record, false otherwise
  # @!method active?

  # Get the name attribute of the +active+ record.
  #
  # @return [Object] the +active+ record's name
  # @!method self.active_name

  # Find the named instance record +canceled+ from the database.
  #
  # @return [Status] the +canceled+ record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.canceled

  # Check if this record is the +canceled+ record.
  #
  # @return [Boolean] true if this is the +canceled+ record, false otherwise
  # @!method canceled?

  # Get the name attribute of the +canceled+ record.
  #
  # @return [Object] the +canceled+ record's name
  # @!method self.canceled_name

  # Find the named instance record +completed+ from the database.
  #
  # @return [Status] the +completed+ record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.completed

  # Check if this record is the +completed+ record.
  #
  # @return [Boolean] true if this is the +completed+ record, false otherwise
  # @!method completed?

  # Get the name attribute of the +completed+ record.
  #
  # @return [Object] the +completed+ record's name
  # @!method self.completed_name

  # Find the named instance record +failed+ from the database.
  #
  # @return [Status] the +failed+ record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.failed

  # Check if this record is the +failed+ record.
  #
  # @return [Boolean] true if this is the +failed+ record, false otherwise
  # @!method failed?

  # Get the name attribute of the +failed+ record.
  #
  # @return [Object] the +failed+ record's name
  # @!method self.failed_name

  # Find the named instance record +pending+ from the database.
  #
  # @return [Status] the +pending+ record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.pending

  # Check if this record is the +pending+ record.
  #
  # @return [Boolean] true if this is the +pending+ record, false otherwise
  # @!method pending?

  # Get the name attribute of the +pending+ record.
  #
  # @return [Object] the +pending+ record's name
  # @!method self.pending_name
end
# End autogenerated YARD docs
