# frozen_string_literal: true

class Status < ActiveRecord::Base
  include SupportTableData

  self.support_table_key_attribute = :code
  add_support_table_data "statuses.yml"
  named_instance_attribute_helpers :name
end

# Begin autogenerated YARD docs
class Status
  # Find the active record from the database.
  #
  # @return [Status] the active record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.active

  # Check if this record is the active record.
  #
  # @return [Boolean] true if this is the active record, false otherwise
  # @!method active?

  # Get the active record's name.
  #
  # @return [Object] the active record's name
  # @!method active_name

  # Find the canceled record from the database.
  #
  # @return [Status] the canceled record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.canceled

  # Check if this record is the canceled record.
  #
  # @return [Boolean] true if this is the canceled record, false otherwise
  # @!method canceled?

  # Get the canceled record's name.
  #
  # @return [Object] the canceled record's name
  # @!method canceled_name

  # Find the completed record from the database.
  #
  # @return [Status] the completed record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.completed

  # Check if this record is the completed record.
  #
  # @return [Boolean] true if this is the completed record, false otherwise
  # @!method completed?

  # Get the completed record's name.
  #
  # @return [Object] the completed record's name
  # @!method completed_name

  # Find the failed record from the database.
  #
  # @return [Status] the failed record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.failed

  # Check if this record is the failed record.
  #
  # @return [Boolean] true if this is the failed record, false otherwise
  # @!method failed?

  # Get the failed record's name.
  #
  # @return [Object] the failed record's name
  # @!method failed_name

  # Find the pending record from the database.
  #
  # @return [Status] the pending record
  # @raise [ActiveRecord::RecordNotFound] if the record does not exist
  # @!method self.pending

  # Check if this record is the pending record.
  #
  # @return [Boolean] true if this is the pending record, false otherwise
  # @!method pending?

  # Get the pending record's name.
  #
  # @return [Object] the pending record's name
  # @!method pending_name
end
# End autogenerated YARD docs
