# frozen_string_literal: true

module SupportTableData
  module Documentation
    # Generates RBS type signatures for the dynamically-defined named instance
    # helper methods on a support table model.
    class RbsDoc
      # @param klass [Class] The model class to generate signatures for
      def initialize(klass)
        @klass = klass
      end

      # Render the full RBS file content for the model, including the class
      # declaration. Returns nil when the model has no named instances.
      #
      # @return [String, nil]
      def signatures
        instance_names = klass.instance_names
        return nil if instance_names.empty?

        body_lines = []
        instance_names.sort.each_with_index do |name, idx|
          body_lines << "" unless idx.zero?
          body_lines.concat(instance_signatures(name))
        end

        <<~RBS
          # Generated by support_table_data - do not edit by hand.
          # To update, run `bundle exec rake support_table_data:rbs`.
          class #{klass.name}
          #{body_lines.map { |line| line.empty? ? "" : "  #{line}" }.join("\n")}
          end
        RBS
      end

      private

      attr_reader :klass

      def instance_signatures(name)
        lines = []
        lines << "def self.#{name}: () -> #{klass.name}"
        lines << "def #{name}?: () -> bool"
        klass.support_table_attribute_helpers.each do |attribute_name|
          return_type = TypeInference.rbs_type(TypeInference.column_type(klass, attribute_name))
          lines << "def self.#{name}_#{attribute_name}: () -> #{return_type}"
        end
        lines
      end
    end
  end
end
